# Tensorflow Basics

## References:
1. https://github.com/aladdinpersson/Machine-Learning-Collection/tree/master/ML/TensorFlow

In [1]:
import os
import tensorflow as tf

In [19]:
# Initialization

## manual initialization
x = tf.constant(4) # Scalar
print(x)
x = tf.constant(4,shape=(1,1),dtype=tf.float32) # 1x1 matrix
print(x)
x = tf.constant([[1,2,3],[4,5,6]]) 
print(x)

## simple initialization
x = tf.ones((3,3))
print(x)
x = tf.zeros((2,3))
print(x)
x = tf.eye(3) #identity matrix
print(x)

## random
x = tf.random.normal((3,3),mean=0,stddev=1)
print(x)
x = tf.random.uniform((3,3),minval=0,maxval=1)
print(x)

## range
x = tf.range(9)
print(x)
x = tf.range(start=1,limit=10,delta=2)
print(x)

## change type
x = tf.cast(x,dtype=tf.float64)
print(x)


tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor([[4.]], shape=(1, 1), dtype=float32)
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[-2.4164937   1.2460254  -0.9171574 ]
 [ 0.2263783   0.6572247  -2.523082  ]
 [ 0.24824394  0.9065302  -2.8451877 ]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[0.81311285 0.8083141  0.572189  ]
 [0.61754405 0.84401464 0.8732393 ]
 [0.6293386  0.88741946 0.2513144 ]], shape=(3, 3), dtype=float32)
tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)
tf.Tensor([1 3 5 7 9], shape=(5,), dtype=int32)
tf.Tensor([1. 3. 5. 7. 9.], shape=(5,), dtype=float64)


In [3]:
# Operations

x = tf.constant([1,2,3])
y = tf.constant([9,8,7])

# Element wise

z = tf.add(x,y) # x + y
z = tf.subtract(x,y) # x - y
z = tf.multiply(x,y) # x*y
z = tf.dividie(x,y) # x/y


z = tf.tensorfot(x,y,axes=1)
z = tf.reduce_sum(x*y,axis=0)

z = x**5

x = tf.random.normal((2,3))
y = tf.random.normal((3,4))
z = tf.matmul(x,y) # x @ y



In [25]:
# Indexing

x = tf.constant([0,1,2,3,4,5,6])
print(x[:])
print(x[2:4])
print(x[::2])
print(x[::-1])


indices = tf.constant([0,3])
x_ind = tf.gather(x,indices)
print(x_ind)

tf.Tensor([0 1 2 3 4 5 6], shape=(7,), dtype=int32)
tf.Tensor([2 3], shape=(2,), dtype=int32)
tf.Tensor([0 2 4 6], shape=(4,), dtype=int32)
tf.Tensor([6 5 4 3 2 1 0], shape=(7,), dtype=int32)
tf.Tensor([0 3], shape=(2,), dtype=int32)


In [26]:
# Reshaping

x = tf.range(9)
print(x)
x = tf.reshape(x, (3,3))
print(x)

x = tf.transpose(x, perm=[1,0])
print(x)

tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)
tf.Tensor(
[[0 1 2]
 [3 4 5]
 [6 7 8]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[0 3 6]
 [1 4 7]
 [2 5 8]], shape=(3, 3), dtype=int32)
